name: Haroun

on:
  push:
    branches:
      - 'haroun'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-3
      FRONT_IMAGE_NAME: clickcat-frontend
      BACK_IMAGE_NAME: clickcat-backend

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
      - name: Install Grype
        run: |
          mkdir -p "$HOME/bin"
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh \
            | sh -s -- -b "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Run Grype
        run: |
          grype . --fail-on medium -o table


      # 2. Configure AWS credentials via secrets
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
            role-to-assume: arn:aws:iam::171171308689:role/GitHubActionsRole
            aws-region: eu-west-3

      # 3. Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Test units
        working-directory: backend
        run: |
          npm ci
          npm test

          
      # 5. Define image URIs
      - name: Set image names
        run: |
          echo "FRONT_IMAGE=${{ steps.login-ecr.outputs.registry }}/hymaia/clic-cat-front:haroun" >> $GITHUB_ENV
          echo "BACK_IMAGE=${{ steps.login-ecr.outputs.registry }}/hymaia/clic-cat-back:haroun" >> $GITHUB_ENV

      - name: Push and build front to ECR
        run: |
          docker build -t $FRONT_IMAGE ./frontend
          docker push $FRONT_IMAGE

      - name: Push and build back to ECR
        run: |
          docker build -t $BACK_IMAGE ./backend
          docker push $BACK_IMAGE
